spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: saturn_bank
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    schemas: saturn_bank
  mvc:
    hiddenmethod:
      filter:
        enabled: true
logging:
  level:
    com.saturn_bank.operator: DEBUG