
ALTER TABLE bank_user ADD COLUMN last_login TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE bank_user ADD COLUMN last_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE bank_user ALTER COLUMN registration_date SET DEFAULT CURRENT_TIMESTAMP;
