
ALTER TABLE card DROP COLUMN IF EXISTS percent;

ALTER TABLE card DROP COLUMN IF EXISTS type;

ALTER TABLE card ALTER COLUMN number SET DATA TYPE VARCHAR(16);

ALTER TABLE card ALTER COLUMN pincode SET DATA TYPE VARCHAR(4);

ALTER TABLE card ALTER COLUMN cvv2 SET DATA TYPE VARCHAR(3);
