name: project-test
on: push
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Compile
        run: mvn --batch-mode --update-snapshots compile
      - name: Test
        run: mvn --batch-mode --update-snapshots test